# https://travis-ci.org/burgerbecky/pyburger
language: python
python:
  - "2.6"
  - "2.7"
	- "3.2"
	- "3.3"
  - "3.4"
	- "3.5"
	- "3.6"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"

# Log these
before_install:
  - python --version
  - uname -a

# command to install dependencies
install: 
	- pip install -U setuptools
	- pip install .
  - virtualenv --version
  - easy_install --version
  - pip --version

notifications:
  email:
    on_success: always
    on_failure: always
