# https://travis-ci.org/burgerbecky/pyburger
sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy

# Log these
before_install:
  - python --version
  - uname -a
  - pyenv versions

# command to install dependencies
install: 
  - pip install -U setuptools
  - pip install -U tox
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version

script:
  - tox

after_failure:
  - more temp/tox/log/* | cat
  - more temp/tox/*/log/* | cat

notifications:
  email:
    on_success: change
    on_failure: always
