# https://travis-ci.org/burgerbecky/pyburger
# Docs for Travis https://docs.travis-ci.com/

# Python testing
language: python

# Cache the python pip and environment folders
cache:
  directories:
    - "$HOME/.cache/pip"
    - "$HOME/.pyenv"

# Only track the master branch, don't process pull requests
branches:
  only:
    - master

# Allow apt-update
addons:
  apt:
    update: true

# Test on Linux and MacOS versions of Python
# Windows is tested at Olde Skuul

matrix:
  include:
    - name: "Python3.4.10 on macOS"
      os: osx
      language: generic
      env:
        - TOXENV=py34
        - PYENV_VERSION=3.4.10
      before_install:
        - brew install openssl readline
        - brew outdated pyenv || brew upgrade pyenv
        - eval "$(pyenv init -)"
        - pyenv install -s $PYENV_VERSION

# Before installing python packages, make sure python is present
#before_install:
#  # macOS needs some pyenv love. Note, not all Linux systems have pyenv, so test for
#  # the command before executing it.
#  - export
#  - |
#    if (command -v pyenv >/dev/null); then
#      pyenv versions
#      pyenv install --list
#    fi
#  - |
#    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
#      brew uninstall pyenv
#      brew install --ignore-dependencies pyenv
#      eval "$(pyenv init -)"
#      pyenv install -s $PYENV_VERSION
#    fi
#  - python --version
#  - uname -a
#  - echo $PATH
#  # Debug spew for linux
#  - |
#    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
#      lsb_release -a
#      readlink -f `which python`
#      ls $(dirname $(readlink -f `which python`))
#    fi

# Install python packages needed for this test and get versions for log
install:
  - pip install .
  - pip install tox-travis wheel codecov coverage pathlib2
  - virtualenv --version
  - easy_install --version
  - pip --version
  - tox --version

# Tox does all the work
script:
  - tox

# Output the errors, if any
after_failure:
  - more temp/tox/log/* | cat
  - more temp/tox/*/log/* | cat

# Send a pass/fail to us
notifications:
  slack:
    rooms:
      secure: T4nFowKbMzdZikD9D0kKg3CYV/NVtypUrfj5NruaZgsArw3Fo0RZj1/CQacXVR8qWBGjpqxwhDDkBEKFjq5e/++GsrUxoLL+Rgz8hn8VVUgV4q8+I7W4WDPybc1pEervJNqqwCq7oCiNen4ZrKzojVuNhO9HVAEDXRNfHzM9k/GvIOOpQzK6QB8tgfXTjoT8MZL5MjBvzFje755XgytELXlgCmcd+2wDXAUBwlgfxMtGC7UZhng5fS/6JmYYoBLATebpKMLUPcLbfHRZ3vb8x2fKnEDXF1YSAjry+Ade8bj/CdoM2SBZjjhsh7L+EoveWY0SXXFdtqjFMZu6zLUTRhACpmID/ANYjZYCUyeNIOzjNml1WhxnD11LGYhmB3V7164FEYdxtq5Z1QSwsH1cmA5u8loitM9nkl1wgc+IBtlrNTpDj7S75iRFxa4mr5hZfBADJy9Tpm5GzX+i/14zYFcE+0f6CnWebGfcTd9Js+vKIKoa4ttoXNhGERBsLy5S2QcBRS5yqSh8/dgi0GsnRBYYEfpOdV9H5mgq4WNVJnsntANwYk/Q9FvTmrrbnteb1oY8Tvf4GvaHioKNLbqbTXNSTdFozbrYLPrNoFGDGQBl767JBtQChcnfsHv78c3BluaLlCU8ikwYzJsrx9KqpXWuc06c+JGVC1qVLR9kZcA=
    on_success: always
    on_failure: always
  email:
    on_success: change
    on_failure: always
